CREATE TABLE ZONA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL UNIQUE,
    descricao VARCHAR(255) NOT NULL
);

CREATE TABLE MOTO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    modelo VARCHAR(255) NOT NULL,
    placa VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    zona_id BIGINT NOT NULL,
    FOREIGN KEY (zona_id) REFERENCES ZONA(id)
);

CREATE TABLE FUNCIONARIO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cargo VARCHAR(255) NOT NULL
);

CREATE TABLE USUARIO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(255) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    perfil VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE MOVIMENTACAO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    moto_id BIGINT,
    zona_origem_id BIGINT,
    zona_destino_id BIGINT,
    descricao VARCHAR(255),
    data_hora TIMESTAMP,
    FOREIGN KEY (moto_id) REFERENCES MOTO(id),
    FOREIGN KEY (zona_origem_id) REFERENCES ZONA(id),
    FOREIGN KEY (zona_destino_id) REFERENCES ZONA(id)
);